### ISSUE TITLE
Are ground truth images necessary? And has anyone succeeded in running the code on Windows OS?

### ISSUE THREAD

**Issue by zelenooki87** [ArcticHare105/S3Diff#1]
?

**Comment by ArcticHare105** [comment]
During inference, ground-truth images are not required. If the GT folder is not provided, the evaluation will only report scores for non-reference metrics.

**Comment by zelenooki87** [comment]
Thank you for your kindly response.
So, I can inference your model like, for example Osediff? (on only LR images given as input)
another thing, I am pretty sure I have correctly setted up env conda on my windows build. triton etc compiled as needed. Everything is there. Sd turbo and pkl models grabbed, downloaded and putted in folders and pointed in config file input LR paths as well.
run_inference.sh file in my case is like:
`accelerate launch --num_processes=1 --gpu_ids="0," --main_process_port 29300 src/inference_s3diff.py \
    --sd_path="C:\Users\Miki\S3Diff\models\sd-turbo" \
    --de_net_path="assets/mm-realsr/de_net.pth" \
    --pretrained_path="C:\Users\Miki\S3Diff\models\s3diff.pkl" \
    --output_dir="./output" \
    --ref_path="./output2"
`


Do I need P. weight from assets/mm-realsr/de_net.pth line? And where I can get it?
Error I am receiving in conda env:
sh run_inference.sh
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_machines` was set to a value of `1`
        `--mixed_precision` was set to a value of `'no'`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "C:\Users\Miki\S3Diff\src\inference_s3diff.py", line 22, in <module>
    import utils.misc as misc
ModuleNotFoundError: No module named 'utils.misc'
Traceback (most recent call last):
  File "C:\Users\Miki\anaconda3\envs\s3diff\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Miki\anaconda3\envs\s3diff\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Miki\anaconda3\envs\s3diff\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "C:\Users\Miki\anaconda3\envs\s3diff\lib\site-packages\accelerate\commands\accelerate_cli.py", line 48, in main
    args.func(args)
  File "C:\Users\Miki\anaconda3\envs\s3diff\lib\site-packages\accelerate\commands\launch.py", line 1174, in launch_command
    simple_launcher(args)
  File "C:\Users\Miki\anaconda3\envs\s3diff\lib\site-packages\accelerate\commands\launch.py", line 769, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Miki\\anaconda3\\envs\\s3diff\\python.exe', 'src/inference_s3diff.py', '--sd_path=C:\\Users\\Miki\\S3Diff\\models\\sd-turbo', '--de_net_path=assets/mm-realsr/de_net.pth', '--pretrained_path=C:\\Users\\Miki\\S3Diff\\models\\s3diff.pkl', '--output_dir=./output', '--ref_path=./output2']' returned non-zero exit status 1.



conda list report:
https://pastebin.com/MAv40wb1


Please any advices?
I was so excited to try this project. Cause Gigant like Huawei envolved in this. :)))))I)

**Comment by ArcticHare105** [comment]
1. Yes, you can evaluate with only LR images as input.
2. We have provided the checkpoint of the degradation estimation network, trained by mm-real, in `assets/mm-real`.
3. It seems you've encountered a warning from accelerate, which would not affect the execution of your code. If you would like to eliminate this warning, you can first run `accelerate config`. This command allows you to configure these parameters interactively. Or you explicitly pass values for these parameters when launching your script, like:
`accelerate launch --num_processes=1 --mixed_precision=no --dynamo_backend=no ...`.
4. You should first run `pip install -e .`, so Python will recognize the module `utils.misc` directly from the source files in your project directory.

**Comment by zelenooki87** [comment]
I was not able to run code on Windows.
Ubuntu installation did the trick.
Results are truly awesome! Thanks for wonderful work!
better than Osediff and more realistic!
 But, please.
How can I use mixed precision for faster inference:
Again I am getting:


(s3diff) milan@milan-MS-7D75:~/S3Diff$ sh run_inference.sh
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/home/milan/anaconda3/envs/s3diff/lib/python3.10/site-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
/home/milan/anaconda3/envs/s3diff/lib/python3.10/site-packages/accelerate/accelerator.py:412: UserWarning: `log_with=wandb` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
{'dynamic_thresholding_ratio', 'rescale_betas_zero_snr', 'clip_sample_range', 'thresholding', 'variance_type'} was not found in config. Values will be initialized to default values.
[Tiled VAE]: input_size: torch.Size([1, 3, 1920, 2560]), tile_size: 1024, padding: 32
[Tiled VAE]: split to 2x3 = 6 tiles. Optimal tile size 832x928, original tile size 1024x1024
[Tiled VAE]: Executing Encoder Task Queue: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 546/546 [00:11<00:00, 48.73it/s]
[Tiled VAE]: Done in 11.391s, max VRAM alloc 7381.718 MB
[Tiled Latent]: the input size is 1920x2560, need to tiled
[Tiled VAE]: input_size: torch.Size([1, 4, 240, 320]), tile_size: 224, padding: 11


Look at these:
	`--mixed_precision` was set to a value of `'no'`
	`--dynamo_backend` was set to a value of `'no'`

Do I in fact, need to install cuda toolkit and cudnn as well?
Only what I did is to setup Ubuntu, latest Nvidia drivers and conda and environment.

If I need to install officially cuda toolkit, please tell me which version? And of course I will add it to path variables.
 
And please, modify code and add tiling function. :)))))
Cause I am getting OOM errors with RTX 3090, 64GB DDR5 and Ryzen 7950X.


Thank you again for fantastic work!

**Comment by zelenooki87** [comment]
To answer myself, just added argument --mixed_precision="bf16"
Everything flies. Thanks.
I will try to implement ffmpeg function to upscale video files like I did in Osediff. Stay tuned :)

**Comment by ArcticHare105** [comment]
I'll close this issue for now. If you have any further questions, feel free to reopen it.

**Comment by zelenooki87** [comment]
I managed to get it running on Windows as well, which is great! However, I'm encountering an issue with a loop in the code where ffmpeg, after successfully extracting frames and upscaling them, keeps repeating itself. Instead of encoding the video, the upscaling process restarts and the files are overwritten. I would be very grateful if you could help me resolve this problem.

I wrote a script for Osediff, whose architecture, as far as I understand, partly served as the basis for your training model. By the way, I want to congratulate you on the achieved result! The consistency of video frames is truly impressive and significantly better compared to Osediff.

I'm wondering if you would be interested in taking a look at my Osediff script and if we could try to create a script for S3DIFF together? That would be fantastic!

Thank you very much in advance!

https://pastebin.com/XdNZAKr3

**Comment by AIisCool** [comment]
> I managed to get it running on Windows

@zelenooki87 What did you do to get it working on Windows?

**Comment by zelenooki87** [comment]
@AIisCool 
The installation process was quite challenging and required several non-standard steps. I initially attempted to install the packages listed in requirements.txt, but quickly encountered compatibility issues. PyTorch installed by default without CUDA support, so I had to uninstall it and manually install the latest official version with CUDA 12.4 support. I installed Xformers using the following command: pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu124.

Diffusers also caused problems, requiring me to revert to an older version specified in requirements.txt. I resolved an error with the Basicsr library by modifying the eighth line of code in the degradations.py file within the conda environment (see [this link](https://www.google.com/url?sa=E&q=https%3A%2F%2Fgithub.com%2FAUTOMATIC1111%2Fstable-diffusion-webui%2Fissues%2F13985) for more details). It also seems that downgrading NumPy to version 1.26.4 was necessary due to incompatibilities with newer versions.

After these adjustments, I ran pip install -e .. The entire conda environment is set up with Python 3.10. Triton required manual installation of a precompiled wheel downloaded from [this link](https://www.google.com/url?sa=E&q=https%3A%2F%2Fhuggingface.co%2Fmadbuda%2Ftriton-windows-builds).

Additional recommendations for successful installation:

Install Visual Studio Build Tools (Community Edition is free) with the C++ compiler and configure its path in the system environment variables.

Update NVIDIA drivers to the latest version.

Install CUDA Toolkit 12.6.2, along with cuDNN and TensorRT. (optional steps)

Just in case, I'm attaching the conda list with a complete list of packages in my environment, which might be helpful if you encounter any unexpected issues.

https://pastebin.com/sM26HHTp

**Comment by AIisCool** [comment]
@zelenooki87 Thanks for the reply, I appreciate it. Wow, that sounds like a complex process. I'll give it a try, though unsure I'll be able to get it to work.

How would you say it compares to this flux based upscaler? https://huggingface.co/jasperai/Flux.1-dev-Controlnet-Upscaler

**Comment by zelenooki87** [comment]
> Are you able to do video frames and have generally consistent results between frames?

Honestly, I'm really impressed with S3Diff. I can't find the original source code for this Flux dev, so I can't try running it locally. The demo on Hugging Face downscales the input images first, making accurate comparison difficult. S3Diff's consistency for video frames is unexpectedly good. However, I'm still struggling to write a video upscaling script. It keeps looping endlessly. Hopefully, the original author can help; that would be great. My main priority is a visually appealing output file that's also very faithful to the original and doesn't hallucinate details like Supir, for example. You should try it on Ubuntu if it's too complicated on Windows. But it's worth a shot on Windows too; it actually runs faster for me there.

**Comment by AIisCool** [comment]
> S3Diff's consistency for video frames is unexpectedly good.

Seems worth a shot for sure.

> I can't find the original source code for this Flux dev

I wound up copying and modifying the gradio demo since the script on their page didn't have an input for a seed value. Though it requires downloading the 54GB entirety of the flux-dev model. So far the only issue I've had is a grid-like pattern with images that aren't very small, which if I increase the steps, it is lessened, but I'm beginning to think that's a flaw in flux.

```
import logging
import random
import warnings
import os
import gradio as gr
import numpy as np
import spaces
import torch
from diffusers import FluxControlNetModel
from diffusers.pipelines import FluxControlNetPipeline
from gradio_imageslider import ImageSlider
from PIL import Image
from huggingface_hub import snapshot_download

css = """
#col-container {
    margin: 0 auto;
    max-width: 512px;
}
"""

if torch.cuda.is_available():
    power_device = "GPU"
    device = "cuda"
else:
    power_device = "CPU"
    device = "cpu"


# Load pipeline
controlnet = FluxControlNetModel.from_pretrained(
  "./jasperai/Flux.1-dev-Controlnet-Upscaler",
  torch_dtype=torch.bfloat16
)
pipe = FluxControlNetPipeline.from_pretrained(
  "./black-forest-labs/FLUX.1-dev",
  controlnet=controlnet,
  torch_dtype=torch.bfloat16
)

pipe.enable_sequential_cpu_offload()

MAX_SEED = 1000000
MAX_PIXEL_BUDGET = 7680 * 7680


def process_input(input_image, upscale_factor, **kwargs):
    w, h = input_image.size
    w_original, h_original = w, h
    aspect_ratio = w / h

    was_resized = False

    if w * h * upscale_factor**2 > MAX_PIXEL_BUDGET:
        warnings.warn(
            f"Requested output image is too large ({w * upscale_factor}x{h * upscale_factor}). Resizing to ({int(aspect_ratio * MAX_PIXEL_BUDGET ** 0.5 // upscale_factor), int(MAX_PIXEL_BUDGET ** 0.5 // aspect_ratio // upscale_factor)}) pixels."
        )
        gr.Info(
            f"Requested output image is too large ({w * upscale_factor}x{h * upscale_factor}). Resizing input to ({int(aspect_ratio * MAX_PIXEL_BUDGET ** 0.5 // upscale_factor), int(MAX_PIXEL_BUDGET ** 0.5 // aspect_ratio // upscale_factor)}) pixels budget."
        )
        input_image = input_image.resize(
            (
                int(aspect_ratio * MAX_PIXEL_BUDGET**0.5 // upscale_factor),
                int(MAX_PIXEL_BUDGET**0.5 // aspect_ratio // upscale_factor),
            )
        )
        was_resized = True

    # resize to multiple of 8
    w, h = input_image.size
    w = w - w % 8
    h = h - h % 8

    return input_image.resize((w, h)), w_original, h_original, was_resized


@spaces.GPU#(duration=42)
def infer(
    seed,
    randomize_seed,
    input_image,
    num_inference_steps,
    upscale_factor,
    controlnet_conditioning_scale,
    progress=gr.Progress(track_tqdm=True),
):
    if randomize_seed:
        seed = random.randint(0, MAX_SEED)
    true_input_image = input_image
    input_image, w_original, h_original, was_resized = process_input(
        input_image, upscale_factor
    )

    # rescale with upscale factor
    w, h = input_image.size
    control_image = input_image.resize((w * upscale_factor, h * upscale_factor))

    generator = torch.Generator().manual_seed(seed)

    gr.Info("Upscaling image...")
    image = pipe(
        prompt="((Photorealistic))",
        control_image=control_image,
        controlnet_conditioning_scale=controlnet_conditioning_scale,
        num_inference_steps=num_inference_steps,
        guidance_scale=3.5,
        height=control_image.size[1],
        width=control_image.size[0],
        generator=generator,
    ).images[0]

    if was_resized:
        gr.Info(
            f"Resizing output image to targeted {w_original * upscale_factor}x{h_original * upscale_factor} size."
        )

    # resize to target desired size
    image = image.resize((w_original * upscale_factor, h_original * upscale_factor))
    image.save("output.png")
    # convert to numpy
    return [true_input_image, image, seed]


with gr.Blocks(css=css) as demo:
    # with gr.Column(elem_id="col-container"):
    gr.Markdown(
        f"""
    # ⚡ Flux.1-dev Upscaler ControlNet ⚡
    """
    )

    with gr.Row():
        run_button = gr.Button(value="Run")

    with gr.Row():
        with gr.Column(scale=4):
            input_im = gr.Image(label="Input Image", type="pil")
        with gr.Column(scale=1):
            num_inference_steps = gr.Slider(
                label="Number of Inference Steps",
                minimum=8,
                maximum=100,
                step=1,
                value=28,
            )
            upscale_factor = gr.Slider(
                label="Upscale Factor",
                minimum=1,
                maximum=8,
                step=1,
                value=4,
            )
            controlnet_conditioning_scale = gr.Slider(
                label="Controlnet Conditioning Scale",
                minimum=0.1,
                maximum=1.5,
                step=0.1,
                value=0.6,
            )
            seed = gr.Slider(
                label="Seed",
                minimum=0,
                maximum=MAX_SEED,
                step=1,
                value=0,
            )

            randomize_seed = gr.Checkbox(label="Randomize seed", value=False)

    with gr.Row():
        result = ImageSlider(label="Input / Output", type="pil", interactive=True)

    examples = gr.Examples(
        examples=[
        #    [42, False, "examples/image_1.jpg", 28, 4, 0.6],
            [42, False, "examples/image_2.jpg", 28, 4, 0.6],
        #    [42, False, "examples/image_3.jpg", 28, 4, 0.6],
            [42, False, "examples/image_4.jpg", 28, 4, 0.6],
        #    [42, False, "examples/image_5.jpg", 28, 4, 0.6],
        #    [42, False, "examples/image_6.jpg", 28, 4, 0.6],
        ],
        inputs=[
            seed,
            randomize_seed,
            input_im,
            num_inference_steps,
            upscale_factor,
            controlnet_conditioning_scale,
        ],
        fn=infer,
        outputs=result,
        cache_examples="lazy",
    )

    # examples = gr.Examples(
    #     examples=[
    #         #[42, False, "examples/image_1.jpg", 28, 4, 0.6],
    #         [42, False, "examples/image_2.jpg", 28, 4, 0.6],
    #         #[42, False, "examples/image_3.jpg", 28, 4, 0.6],
    #         #[42, False, "examples/image_4.jpg", 28, 4, 0.6],
    #         [42, False, "examples/image_5.jpg", 28, 4, 0.6],
    #         [42, False, "examples/image_6.jpg", 28, 4, 0.6],
    #         [42, False, "examples/image_7.jpg", 28, 4, 0.6],
    #     ],
    #     inputs=[
    #         seed,
    #         randomize_seed,
    #         input_im,
    #         num_inference_steps,
    #         upscale_factor,
    #         controlnet_conditioning_scale,
    #     ],
    # )

    gr.Markdown("**Disclaimer:**")
    gr.Markdown(
        "This demo is only for research purpose. Jasper cannot be held responsible for the generation of NSFW (Not Safe For Work) content through the use of this demo. Users are solely responsible for any content they create, and it is their obligation to ensure that it adheres to appropriate and ethical standards. Jasper provides the tools, but the responsibility for their use lies with the individual user."
    )
    gr.on(
        [run_button.click],
        fn=infer,
        inputs=[
            seed,
            randomize_seed,
            input_im,
            num_inference_steps,
            upscale_factor,
            controlnet_conditioning_scale,
        ],
        outputs=result,
        show_api=False,
        # show_progress="minimal",
    )

demo.launch(
    server_name="0.0.0.0" if os.getenv('GRADIO_LISTEN', '') != '' else "127.0.0.1",
    share=True,
    root_path=f"/{os.getenv('GRADIO_PROXY_PATH')}" if os.getenv('GRADIO_PROXY_PATH') else ""
)
```
The requirments:

- accelerate
- diffusers @ git+https://github.com/initml/diffusers.git@main
- torch==2.0.1
- transformers >= 4.34.0
- xformers
- ftfy
- spaces
- peft >= 0.6.0
- sentencepiece==0.2.0
- optimum
- beautifulsoup4
- gradio==4.29.0
- gradio_imageslider

**Comment by zelenooki87** [comment]
Ough. I tried it. It si OK, but too slow for my expectations.
upscaled only one pic
Comparison
https://imgsli.com/MzAyMDYx
Original
![Photo0001](https://github.com/user-attachments/assets/882cec32-613d-4981-8bff-6519402e692a)
I can share more example of S3diff to you. But unfortunately there are no PM system at github.

**Comment by AIisCool** [comment]
> too slow for my expectations.

Yes, wish it was faster. I see you also get the grid across it. Must be something truly wrong with flux, damn.

Interesting to see S3Diff interpret the nails in an odd way, on the top hand.

Indeed, a PM system would be good!

I am curious, how does it handle this?
![mkv_FFmpegSource2_VOY 03](https://github.com/user-attachments/assets/3b9dd33d-6778-475f-ac86-9ae57919fc68)

I had to crop it for flux, but still wish to compare with the S3Diff, if you don't mind.

This was the output with flux:
![output_VOY 03](https://github.com/user-attachments/assets/b615a938-a7d4-43f6-ae73-bfe0c6f80fce)

**Comment by zelenooki87** [comment]
could you please original source, to postimage site, for example. there are option for original quality
https://postimages.org/sr/
In a meantime I will upscale this compressed and resized from github

**Comment by zelenooki87** [comment]
@AIisCool 
Here you are mate(from github source)

![373185398-3b9dd33d-6778-475f-ac86-9ae57919fc68](https://github.com/user-attachments/assets/2a2e1c65-6cf2-4d4f-9eab-d220fcc0aeaf)

**Comment by zelenooki87** [comment]
> > too slow for my expectations.
> 
> Yes, wish it was faster. I see you also get the grid across it. Must be something truly wrong with flux, damn.
> 
> Interesting to see S3Diff interpret the nails in an odd way, on the top hand.
> 
> Indeed, a PM system would be good!
> 
> I am curious, how does it handle this? ![mkv_FFmpegSource2_VOY 03](https://private-user-images.githubusercontent.com/92149242/373185398-3b9dd33d-6778-475f-ac86-9ae57919fc68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NDYyNTksIm5iZiI6MTcyNzk0NTk1OSwicGF0aCI6Ii85MjE0OTI0Mi8zNzMxODUzOTgtM2I5ZGQzM2QtNjc3OC00NzVmLWFjODYtOWFlNTc5MTlmYzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDA4NTkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NDUyNGRkZjEzNDBkOTA1YzcxYmViZjQ0Yzc2YjE1OGRhN2MzYTdhYWQ0MjYzNzZlMTJmNTZlMzE0Mjg2ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.x9Y0F_vgPKviGeBzC2-tYQ-RGORk4LmK7L6RV5CVaU0)
> 
> I had to crop it for flux, but still wish to compare with the S3Diff, if you don't mind.
> 
> This was the output with flux: ![output_VOY 03](https://private-user-images.githubusercontent.com/92149242/373185532-b615a938-a7d4-43f6-ae73-bfe0c6f80fce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NDYyNTksIm5iZiI6MTcyNzk0NTk1OSwicGF0aCI6Ii85MjE0OTI0Mi8zNzMxODU1MzItYjYxNWE5MzgtYTdkNC00M2Y2LWFlNzMtYmZlMGM2ZjgwZmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDA4NTkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZjM3YTMyNzVjMzM3ZmVmOGUyNTU0MWUwMGQ5OTZhZmQxOTdmM2Y0YWI2ZDE3MDNiMzgwNjJiYjIyZTFkZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pA2jrpOWITT0jpaYSRoi9jUzmKGiD_qj7czdta3yfBM)

nails are interpreted OK, trust me, I have bigger input. Flux removed some colors. :)

**Comment by AIisCool** [comment]
> @AIisCool Here you are mate(from github source)

Thank you. Wow, it is more faithful with the details than flux is. Though I see both struggle with the blue eyes, unless prompted (I had to add it or he had brown eyes with flux the first try).

**Comment by zelenooki87** [comment]
@AIisCool If you want, you can share a short clip, around 5-10 seconds, in 480p or 576p (DVD resolution), so I can try S3Diff and compare it to, say, Topaz Video AI (using the RXL model). It's actually a new model that will be in the next version of Topaz Video AI. (Don't ask how I know, I'm a beta tester :P). I'll then send it to you. You can use something like LosslessCut from GitHub for cutting without quality loss.

**Comment by zelenooki87** [comment]
@AIisCool 
https://i.postimg.cc/3JSpj7S5/mkv-FFmpeg-Source2-VOY-04.png
https://i.postimg.cc/wTvRjZ6W/S01-E03-Parallax-00-00.png

**Comment by zelenooki87** [comment]
How it looks to your eyes?
PS. you have specific taste of upscaling material, friend

**Comment by AIisCool** [comment]
> @AIisCool https://i.postimg.cc/3JSpj7S5/mkv-FFmpeg-Source2-VOY-04.png https://i.postimg.cc/wTvRjZ6W/S01-E03-Parallax-00-00.png

I am amazed! Much better than what I had with flux.

Haha, yes I am a fan of Star Trek. Always sad that they won't remaster the last two "classic" spin-offs, but spend money on newer shows that are not as well written.

One last image to try, if you don't mind. I always find it has issues with his uniform. The ranking on his neck is never made correctly by diffusion.

https://postimg.cc/tYZfCjkZ

I will attempt to get S3Diff working. I hope my 3090 can manage. Looking to eventually upgrade it all with newest AMD CPU and the RTX 5090.

**Comment by zelenooki87** [comment]
I have Ryzen 7950x build, 64GB DDR5, RTX 3090.
As an AI fanatic, I hope so that some day I will have money for something like Hopper or AMD Instinct series( 5-25000$)
Some day... 
But due out of memory errors, and cheap RTX 3090s maybe I will build RIG of 4 or 8.
With 3090 you could upscale with mixed precision up to, I think 2,5MPx-4MPx input. But for bigger sizes there are small tile lines. But for video upscaling and lower resolutions, S3Diff is awesome.
https://i.postimg.cc/sXF3Ym0S/S01-E03-Parallax-00-01.png

**Comment by AIisCool** [comment]
> I have Ryzen 7950x build, 64GB DDR5, RTX 3090.

Similar here @zelenooki87, but I have a 5950x. Debating on if I should get a 9950x, or wait for the 9000X3D series. Though either way, need to get new motherboard and so on. Not that I have the money for any of that now.😆

> https://i.postimg.cc/sXF3Ym0S/S01-E03-Parallax-00-01.png

Incredible. The rank markings are _almost_ as it should be. It should be as it was in the other image of that character, three separate circles, but this is the closest I've ever seen SD get to being correct.

>https://i.postimg.cc/wTvRjZ6W/S01-E03-Parallax-00-00.png

For comparison, flux gave me [this](https://postimg.cc/4n7RrhYV), which is a bit better than what it did with the other one. But still not as good as S3Diff.

**Comment by zelenooki87** [comment]
> > I have Ryzen 7950x build, 64GB DDR5, RTX 3090.
> 
> Similar here @zelenooki87, but I have a 5950x. Debating on if I should get a 9950x, or wait for the 9000X3D series. Though either way, need to get new motherboard and so on. Not that I have the money for any of that now.😆
> 
> > As an AI fanatic, I hope so that some day I will have money for something like Hopper or AMD Instinct series( 5-25000$)
> 
> Perhaps one day!
> 
> > https://i.postimg.cc/sXF3Ym0S/S01-E03-Parallax-00-01.png
> 
> Incredible. The rank markings are _almost_ as it should be. It should be as it was in the other image of that character, three separate circles, but this is the closest I've ever seen SD get to being correct.
> 
> > https://i.postimg.cc/wTvRjZ6W/S01-E03-Parallax-00-00.png
> 
> For comparison, flux gave me [this](https://postimg.cc/4n7RrhYV), which is a bit better than what it did with the other one. But still not as good as S3Diff.

Get S3Diff running and the conda environment set up correctly. Good luck!

**Comment by AIisCool** [comment]
> Get S3Diff running and the conda environment set up correctly. Good luck!

Thank you, attempting to do so now.🫡

**Comment by AIisCool** [comment]
@zelenooki87 I remembered seeing you on the "Enhance Everything" discord, so I sent you a PM.

**Comment by zelenooki87** [comment]
Accepted DM, but not always on Discgord :)
Greetz

**Comment by zhanghaokun2001** [comment]
Hi, I'm running it on Windows system./run_inference
It doesn't work in pycharm or Git Bash, PS E:\S3Diff-main> E:/ ss3diff-main /run_inference
The program run_inference.sh cannot be run: the application location cannot be found. Line :1 Character :1
+ E:/S3Diff-main/run_inference.sh
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
Location Line :1 Character :1
+ E:/S3Diff-main/run_inference.sh
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
+ FullyQualifiedErrorId : NativeCommandFailed

The result of running in pycharm is like this, can you help me run in windows, or tell me about your experience in running t

**Comment by zhanghaokun2001** [comment]
@zelenooki87

**Comment by zhanghaokun2001** [comment]
My run_inference,sh is like this accelerate launch --num_processes=1 --gpu_ids="0," --main_process_port 29300 src/inference_s3diff.py \
--sd_path="path_to_checkpoints/sd-turbo" \
--de_net_path="assets/mm-realsr/de_net.pth" \
--pretrained_path="path_to_checkpoints_folder/model_30001.pkl" \
--output_dir="./output" \
--ref_path="path_to_ground_truth_folder"\    @zelenooki87
