### ISSUE TITLE
Can you show me the SR result of this image?

### ISSUE THREAD

**Issue by ChenhLiwnl** [ArcticHare105/S3Diff#10]
![0801](https://github.com/user-attachments/assets/d7b4e1d9-51e1-4843-b449-a9abfa94f5fb)
I tested it on my environment but cannot get decent results
I'm wondering if it is an issue with my own settings, so I would like to ask you what the result of your super-resolution is.

**Comment by ArcticHare105** [comment]
Could you show your SR results?

**Comment by ArcticHare105** [comment]
![penguin](https://github.com/user-attachments/assets/b310cc09-a88f-4b9a-866f-853587a3a763)
Our result is like this. Did you modify any code?

**Comment by ChenhLiwnl** [comment]
> ![penguin](https://private-user-images.githubusercontent.com/66931185/377382686-b310cc09-a88f-4b9a-866f-853587a3a763.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxNTQ3MDUsIm5iZiI6MTcyOTE1NDQwNSwicGF0aCI6Ii82NjkzMTE4NS8zNzczODI2ODYtYjMxMGNjMDktYTg4Zi00YjlhLTg2NmYtODUzNTg3YTNhNzYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE3VDA4NDAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzZTRmY2I5Zjc3N2ExYzIzNmQ4MzYwNWQwNmZjNjcwYTQ5NTczNzg0N2ZlYzU0Y2IzZjAwOTlkZTg2NjAxNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Z94klxjRWrwLafyAZcke8W81lI2xIhyUBTiXBS5Fumo) Our result is like this. Did you modify any code?

Thank you 
I'm going to check it again, maybe I changed but I didn't realize

**Comment by ArcticHare105** [comment]
I'll close this issue for now. If you have any further questions, feel free to reopen it.
