### ISSUE TITLE
Impact of Online Degradation on Performance Improvement Compared to Offline Degradation

### ISSUE THREAD

**Issue by YaqiWangCV** [ArcticHare105/S3Diff#13]
Currently, the code uses online degradation instead of offline degradation as done in SeeSR/OSEDiff. 

Does this design choice impact performance improvement?"

**Comment by ArcticHare105** [comment]
> Currently, the code uses online degradation instead of offline degradation as done in SeeSR/OSEDiff.
> 
> Does this design choice impact performance improvement?"

I'm not sure how you distinguish between online and offline degradation. Both we and SeeSR/OSEDiff follow the Real-ESRGAN to generate LR images with arbitrary degradations during training.

**Comment by ArcticHare105** [comment]
I'm not sure how you distinguish between online and offline degradation. Both we and SeeSR/OSEDiff follow the Real-ESRGAN to generate LR images with arbitrary degradations during training.
