### ISSUE TITLE
1x, 2x results using the inference_s3diff.py and s3diff.pkl

### ISSUE THREAD

**Issue by ManuBN786** [ArcticHare105/S3Diff#14]
I would like to infer a 1x & 2x SR results too using the provided model 's3diff.pkl'  and   inference_s3diff.py. 

My test image is 128x128. The results of prediction are always 4x (512x512) even if I mention '--scale 1' 

But when I use the 'gradio_s3diff.py'  I can easily get the 1X, 2X results 

![Screenshot from 2024-10-28 13-47-42](https://github.com/user-attachments/assets/8a9f5f44-7cd2-46e3-8b50-e5b7f5cce51a)

The same applies for models trained on custom dataset.

How to infer 1X, 2X results using inference_s3diff.py ?

Thanks in advance.

**Comment by ArcticHare105** [comment]
You can change the argument `sf` in `S3Diff/configs/sr_test.yaml` to 1 or 2 to obtain 1X or 2X results.
