### ISSUE TITLE
Training  time 

### ISSUE THREAD

**Issue by zzzzzero** [ArcticHare105/S3Diff#15]
Thank you for open-sourcing the training code. 
During my training, I found that one training step takes about 8 seconds，it‘s weired. I have used the same training data and trained with 4 A100 GPUs for around 10,000 steps, but I noticed that the results on the validation set were quite poor, and the perceptual loss did not decrease significantly. Moreover, I tried not using GAN loss and found that the network still converges very slowly.So, I wanted to ask how long the network training takes.

**Comment by zzzzzero** [comment]
> We utilize four A100 GPUs to train our model, which takes approximately 100 minutes for 500 steps. As illustrated in Figure 9 of our paper, the model converges rapidly, reaching a performance plateau around 5,000 steps, after which improvements occur more gradually.

Thank you so much for your quick reply. I tried switching PyTorch from 2.1.0 to 2.0.1 and downgraded PEFT from 0.12.0 to 0.10.0. I didn't set the --mixed_precision option in the training script to FP16 (doing so resulted in a ValueError: Attempting to unscale FP16 gradients). Currently, the loss and eval results look normal, but the training speed has decreased from 8s/step to 18s/step. If possible, I suggest you provide detailed information about the versions of PyTorch, Accelerate, and PEFT.

**Comment by ArcticHare105** [comment]
accelerate=0.29.2
torch=2.1.0
peft=0.10.0

We do not use FP16 during training.
