### ISSUE TITLE
Possible to disable tiling? Also can you implement wavelet color fix?

### ISSUE THREAD

**Issue by AIisCool** [ArcticHare105/S3Diff#2]
The results are **truly amazing**!🤩 However, I am noticing the colors seem overly saturated. Is it possible to implement a [wavelet color fix as seen in SeeSR](https://github.com/cswry/SeeSR/blob/main/utils/wavelet_color_fix.py)? The over saturated colors remind me of when "no fix" is used in SeeSR.

As for the tiling, I am noticing both the tiling being present and also causing strange effects. Perhaps either a way to disable or increase the tile size?

For example this input:
![mkv_FFmpegSource2_VOY 01](https://github.com/user-attachments/assets/0e7c7991-e9fa-4fed-be17-37661a88b076)

Becomes like this:
![mkv_FFmpegSource2_VOY 01](https://github.com/user-attachments/assets/e5aede42-c9c5-4fe8-8cf3-7296d58d38c0)

Almost looks like he has a sunburn.

I noticed if I give it the cropped version, it is not as "sunburnt":
![mkv_FFmpegSource2_VOY 00 01](https://github.com/user-attachments/assets/664d8a19-4cf1-4334-8d0d-7fdbfb195ad9)

Here you can see the tiling causing strange effects.

See this input:
![S01E03 Parallax 02](https://github.com/user-attachments/assets/3b6858c3-6ac6-412f-a4bd-919ec8ef3f9c)

The full output:
![S01E03 Parallax 02](https://github.com/user-attachments/assets/996c7f6c-2462-431f-b15c-a4a6ae787a32)

The area of the background behind her is much lighter than the rest of the background. I also noticed one of the monitors in the background is brought into focus, but I think that is an issue I have seen at times with stable diffusion.

However if I crop it, it stays the color it should be:
![S01E03 Parallax 02 00](https://github.com/user-attachments/assets/8beb24bf-3f5c-41ed-8543-2d73a5b1031f)

If I make that crop 100px larger, it starts to have color issues:
![S01E03 Parallax 02 01](https://github.com/user-attachments/assets/38b774e2-0aa0-4d55-932b-2c5d61e26e97)

**Comment by AIisCool** [comment]
@ArcticHare105 I've tried "bypassing" the tiling by increasing `--latent_tiled_size` to a value larger than the input image. While it does remove the tiling issue, the results are not nearly as good as with tiling used.

Is there any way to enhance the image to the same quality as it would be when tiled, but not tile it? Or not have the tiling affect the output image as it has?

Take this cropped portion of an input image:
![image](https://github.com/user-attachments/assets/5280c7dd-26b7-405b-afa6-11fe5da01987)

The output has a large dark square on it:
![image](https://github.com/user-attachments/assets/b3552d15-3a62-4964-947d-01757a7ce8bf)

If I increase `--latent_tiled_size` the dark square is gone, but the overall sharpness of the image is lessened. I've also tried inverting the image color and mirroring the image, but the square remains in the same area.

**Comment by ArcticHare105** [comment]
@AIisCool Sorry for the late response. We will add color correction as in SeeSR soon.

For the tiling issue, since S3Diff is trained to upscale from 128x128 to 512x512, increasing the tile size results in a resolution much larger than what it was trained for. This can lead to issues for Diffusion-based models, similar to those seen in [ScaleCrafter](https://yingqinghe.github.io/scalecrafter/). Although ScaleCrafter doesn't specifically address the super-resolution (SR) problem, I believe the similar issue would occur in SR when the inference resolution significantly exceeds the trained resolution.

You could first try only to increase the overlap size to remove the block effect.

**Comment by ArcticHare105** [comment]
@AIisCool We have added the color correction, please try our updated code. I have run one of your provided images using wavelet color correction, the result is shown below, you can disable the color correction or change to adain by modifying the argument `align_method` in `run_inference.sh`.
![woman](https://github.com/user-attachments/assets/0545c2b2-0f7d-4d6d-96c4-bab41e608646)

**Comment by AIisCool** [comment]
@ArcticHare105 Thank you! No worries for the delay, I am sure you are busy.

I downloaded the updates but for some reason I get:

```
[Tiled VAE]: Done in 12.132s, max VRAM alloc 14452.763 MB
[Tiled VAE]: Done in 23.332s, max VRAM alloc 2871.568 MB
Traceback (most recent call last):
  File "C:\S3Diff\src\inference_s3diff.py", line 213, in <module>
    main(args)
  File "C:\S3Diff\src\inference_s3diff.py", line 194, in main
    output_pil = wavelet_color_fix(output_pil, im_lr_resize)
NameError: name 'wavelet_color_fix' is not defined
```

I will try reinstalling the conda env, though that will take a bit of time to do on Windows again.

**Comment by zelenooki87** [comment]
@AIisCool Sorry to hear, that code doesnt work for you now.
On my side, Windows build, working okay.

**Comment by zelenooki87** [comment]
Ough... Something is wrong with wavelet color fix...
<img width="1280" alt="Screenshot-00007" src="https://github.com/user-attachments/assets/ad0e6fd7-53ff-4bb2-a2d1-f0699dc802c5">
<img width="1280" alt="Screenshot-00008" src="https://github.com/user-attachments/assets/a3128d8b-1f6e-40f4-9eb2-bcfd27d580d4">

**Comment by AIisCool** [comment]
> The fix was to add the following import statement at the beginning of the inference_s3diff.py file, along with the other imports:
> after line:
> `import utils.misc as misc`
> add line
> `from utils.wavelet_color import wavelet_color_fix, adain_color_fix`

Haha, I was about to comment the same thing. I looked at the SeeSR code for what might be different.

That said, I ran it and it seems the wavelet color fix seems to be acting strangely.

No fix:
![image](https://github.com/user-attachments/assets/2111be00-8c63-4aa9-923c-caf9a59f1600)

Wavelet:
![image](https://github.com/user-attachments/assets/5b650177-5ff5-4e4f-b4cd-0e7cd21576c0)

Adain:
![image](https://github.com/user-attachments/assets/d2415c3d-8c83-4f15-ab28-3d97fe3d1a1e)
(Adain colors look almost the same as no fix, a bit darker though)

**Comment by ArcticHare105** [comment]
@zelenooki87 @AIisCool Sorry for the mistake, we have added the line `from utils.wavelet_color import wavelet_color_fix, adain_color_fix`.

**Comment by AIisCool** [comment]
@ArcticHare105 It works well! I wonder though, what is causing some strange colors when using wavelet. Without the strange colors, it is almost prefect.

Also I noticed that the monitor in the background is as it should be here:
> ![woman](https://private-user-images.githubusercontent.com/66931185/374021431-0545c2b2-0f7d-4d6d-96c4-bab41e608646.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyODQ3ODAsIm5iZiI6MTcyODI4NDQ4MCwicGF0aCI6Ii82NjkzMTE4NS8zNzQwMjE0MzEtMDU0NWMyYjItMGY3ZC00ZDZkLTk2YzQtYmFiNDFlNjA4NjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA3VDA3MDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNjhiYzFmZjkxYjdjYTFhZTEzZTAzNTZkYmQ3ZjFkMGExMTFmZjIxYWMyOWYzZGZmNzE2NDlhMDc1Yjg3ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1N_-0KJVP6BilrOos_lfLQ3hJU1QNYivQOnS7UIbAz8)

but I still have the issue of it being brought into focus.

![S01E03 Parallax 02](https://github.com/user-attachments/assets/751905b0-1640-4a9e-8dca-a6483ec0bd6c)


Not sure why there is that difference. I have tried different values for `latent_tiled_overlap` but same result.

**Comment by ArcticHare105** [comment]
@AIisCool I use `latent_tiled_size=128` and `latent_tiled_overlap=32` for this image.

**Comment by AIisCool** [comment]
> I use `latent_tiled_size=128` and `latent_tiled_overlap=32` for this image.

@ArcticHare105 That worked! Thank you!🙏 Do you have any ideas regarding the color issues seen here? https://github.com/ArcticHare105/S3Diff/issues/2#issuecomment-2396046991

Should I post the full image?

**Comment by ArcticHare105** [comment]
@AIisCool Actually, I cannot figure out the issue, maybe you need to further describe it, and post the LR image and the full HR image as well.

**Comment by AIisCool** [comment]
@ArcticHare105  
There are areas of green and blue, that aren't present in the original image.

Input:
![S01E03 Parallax 12](https://github.com/user-attachments/assets/fd6cbe58-c718-41f7-ba86-9f526acd9d68)

Output with wavelet:
![S01E03 Parallax 12](https://github.com/user-attachments/assets/8e8cf4b6-9706-4559-b77d-1e7ae8e7ac54)

![S01E03 Parallax 12-](https://github.com/user-attachments/assets/98f295e5-df46-4d91-8304-3ebabdee743b)

**Comment by ArcticHare105** [comment]
@zelenooki87 @AIisCool We've added the Gradio demo. Feel free to try it out and share your feedback if it's convenient.

**Comment by AIisCool** [comment]
Will try it @ArcticHare105 

Last image for the wavelet issue. Wish one of us could figure out the cause. It's so nice to get upscaled images, but something definitely isn't working right with wavelet.

![MTB_BorderControl 133](https://github.com/user-attachments/assets/5c4f251c-e253-4cd4-872d-96948fdfbc78)

![MTB_BorderControl 133](https://github.com/user-attachments/assets/5b7ea532-7521-4e3d-b748-39b7db1c0928)

**Comment by ArcticHare105** [comment]
@AIisCool When decomposing in the frequency domain, the frequency information of different color channels may overlap, leading to crosstalk, which may lead to the issue presented in your images. I have no solution for this issue now, but I think the current generation results are acceptable.

**Comment by AIisCool** [comment]
> When decomposing in the frequency domain, the frequency information of different color channels may overlap, leading to crosstalk, which may lead to the issue presented in your images.

That makes sense @ArcticHare105 . I wish I was more knowledgeable to perhaps try and create a solution. That said, I wonder if changing the colorspace from RGB to HSV or another and then back to RGB for the output, might change anything?

**Comment by ArcticHare105** [comment]
I'll close this issue for now. If you have any further questions, feel free to reopen it.
