### ISSUE TITLE
meet the error: ModuleNotFoundError: No module named 'basicsr'

### ISSUE THREAD

**Issue by dongdk** [ArcticHare105/S3Diff#4]
hi @ArcticHare105 
does it need to install basicsr via pip installation? or just set the path to env?
thanks

**Comment by ArcticHare105** [comment]
@dongdk You need to run `pip install -e .` to include the basicsr in our project.

**Comment by dongdk** [comment]
ok, but after running `pip install -e .`, i meet the problem: `e: 'Conv2d' object has no attribute '_check_forward_args' ...`

**Comment by ArcticHare105** [comment]
I have not met this error before, can you show the whole error message?

**Comment by dongdk** [comment]
it's already the whole error, i have no idea to deal with it. please give me a hand.

**Comment by ArcticHare105** [comment]
What is your pytorch version?

**Comment by dongdk** [comment]
2.0.1+cu117

**Comment by dongdk** [comment]
and these two lines
```
            pos_model_pred = self.unet(lq_latent, self.timesteps, encoder_hidden_states=pos_caption_enc).sample
            neg_model_pred = self.unet(lq_latent, self.timesteps, encoder_hidden_states=neg_caption_enc).sample
```

**Comment by dongdk** [comment]
it maybe the peft version is not matched. i check the `_check_forward_args`  func in peft repo, and find that peft-0.9.0 version does not have it. i will try peft==0.13.0

**Comment by dongdk** [comment]
hi @ArcticHare105 after installing peft==0.13.0 and  run `pip install -e .`, the problem has been solved.

**Comment by ArcticHare105** [comment]
@dongdk Great to hear that the issue has been resolved! If you need any more help, feel free to ask.

**Comment by zhanghaokun2001** [comment]
zimenglan_sysu is your micro signal, I want to add you to ask some questions.

**Comment by dongdk** [comment]
hi @ArcticHare105 below is my installation
```
pip install --user einops==0.6.1
pip install --user numpy==1.24.4
pip install --user open-clip-torch==2.20.0
pip install --user opencv-python==4.6.0.66
pip install --user pillow==9.5.0
pip install --user scipy==1.11.1
pip install --user timm==0.9.2
pip install --user tokenizers

pip install --user torchmetrics==1.0.1
pip install --user torch==2.2.0 torchvision==0.17.0 torchaudio==2.2.0 torchdata==0.8.0
pip install --user transformers==4.35.2 triton==2.2.0 torchtext==0.17.0 peft==0.13.0 diffusers==0.25.1 xformers==0.0.24

pip install --user tqdm==4.65.0

pip install --user urllib3==1.25.4
pip install --user streamlit-keyup==0.2.0
pip install --user lpips
pip install --user pyiqa
pip install --user omegaconf
pip install --user dominate
pip install --user gradio==3.43.1

pip install -e . --user
```

**Comment by qianx77** [comment]
pip install peft==0.13.0 can solve the problem ， thank you very much 

> e: 'Conv2d' object has no attribute '_check_forward_args'
