### ISSUE TITLE
run_inference.sh

### ISSUE THREAD

**Issue by zhanghaokun2001** [ArcticHare105/S3Diff#6]
Hello author, I can't run run_training.sh after following your steps, the error is as follows
PS E:\S3Diff-main> E:/S3Diff-main/run_inference.sh
The program run_inference.sh cannot be run: the application location cannot be found. Line :1 Character :1
+ E:/S3Diff-main/run_inference.sh
Location Line :1 Character :1
+ E:/S3Diff-main/run_inference.sh
+ CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
+ FullyQualifiedErrorId : NativeCommandFailed
I have lpips installed, along with other dependencies, and running this script in Git bash is still getting errors. @ArcticHare105

**Comment by ArcticHare105** [comment]
Sorry, I'm not sure what caused it, I am unfamiliar with how to run it on the Windows system.

**Comment by zhanghaokun2001** [comment]
Okay, so you're operating on linx

**Comment by ArcticHare105** [comment]
> Okay, so you're operating on linx

Yes, but it seems the error is related to your installation and environment, not our code.

**Comment by zhanghaokun2001** [comment]
ok,i will try any other method

**Comment by ArcticHare105** [comment]
I'll close this issue for now. If you have any further questions, feel free to reopen it.
