### ISSUE TITLE
can provide the lr and corresponding generated hr images used in gradio demo?

### ISSUE THREAD

**Issue by dongdk** [ArcticHare105/S3Diff#7]

**Comment by ArcticHare105** [comment]
Do you mean the LR image and the generated HR image shown in the figure of gradio demon of README?

**Comment by ArcticHare105** [comment]
You can find the LR image and the generated image from https://github.com/ArcticHare105/S3Diff/issues/2#issue-2566773484 and https://github.com/ArcticHare105/S3Diff/issues/2#issuecomment-2395859455

**Comment by dongdk** [comment]
ok, but can u put it int the repo? a little bit troublesome to download them by hand. thanks

**Comment by ArcticHare105** [comment]
@dongdk  Sorry, to kept the repo small for easier downloading, we wouldn't put too much images into this repo. I post them to postimg, you can download the [LR image](https://i.postimg.cc/Gtpr7mqF/LR-woman.png) and [HR image](https://i.postimg.cc/Hxstjq6Z/woman.png).

**Comment by dongdk** [comment]
thanks a lot
