### ISSUE TITLE
when 4x sr for 512x512 input image, the process is too slow, any idea to speed up?

### ISSUE THREAD

**Issue by dongdk** [ArcticHare105/S3Diff#8]
hi @ArcticHare105 
i find that when 4x sr for 512x512 input image, the process is too slow, any idea to speed up? i use the default values for these two vars
```
latent_tiled_size=96
latent_tiled_overlap=32
```

btw, can i join your wechat? want to ask u some question, thanks.

**Comment by ArcticHare105** [comment]
It is a common issue for latent space diffusion-based super-resolution. To save memory consumption, we need to split the image into patches before using the VAE encoder. The UNet also processes overlapping patches and then fuses them. The fused output is then divided again for the VAE decoder and finally stitched into the final output. This process takes significantly more time for the default 128x128 input.

**Comment by dongdk** [comment]
get it, thanks a lot.
btw, can u release the 1x and 2x model.

**Comment by ArcticHare105** [comment]
We don't have models for other upscaling factors, we follow previous diffusion-based SR methods to train and test only on the 4x model. I have no idea whether the result would be if the input resolution is smaller than 512x512, but if your input is larger than 512x512, for example, you would like a 256x256 image upscaling to 512x512 in a 2x setting, our method can also handle this.

**Comment by dongdk** [comment]
get it, i will try it, thanks.

**Comment by ArcticHare105** [comment]
I'll close this issue for now. If you have any further questions, feel free to reopen it.
