### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by Fire-friend** [ArcticHare105/S3Diff#9]
Thanks for your amazing work! I am trying to train your model but encountering the following issues:

 ValueError: <class 'diffusers.models.unet_2d_condition.UNet2DConditionModel'> has the config param `addition_embed_type` set to 'text_time' which requires the keyword argument `text_embeds` to be passed in `added_cond_kwargs`

Can you give me some suggestions?

**Comment by ArcticHare105** [comment]
What is your diffusers' version? Is it version 0.25.1?

**Comment by Fire-friend** [comment]
![image](https://github.com/user-attachments/assets/4a368959-67fb-4448-aa70-304240b3573c)
Yes, I have already checked the environment to ensure compliance with the requirements.

**Comment by ArcticHare105** [comment]
I have no idea why the error occurred, but it looks like the argument `addition_embed_type` is changed somewhere to `text_time`, but it should be None. Maybe you can manually modify it to None to temporarily address this issue.
